### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getParameterCount()

### ISSUE THREAD

**Issue by kasnder** [maxmind/GeoIP2-java#234]
Hello,

After updating your library from 2.14 to the latest version 2.15, I experience the following error when running on Android 7:

    java.lang.NoSuchMethodError: No virtual method getParameterCount()I in class Ljava/lang/reflect/Constructor; or its super classes (declaration of 'java.lang.reflect.Constructor' appears in /system/framework/core-oj.jar)
        at com.maxmind.db.Decoder.decodeMapIntoObject(Decoder.java:397)
        at com.maxmind.db.Decoder.decodeMap(Decoder.java:342)
        at com.maxmind.db.Decoder.decodeByType(Decoder.java:162)
        at com.maxmind.db.Decoder.decode(Decoder.java:151)
        at com.maxmind.db.Decoder.decode(Decoder.java:76)
        at com.maxmind.db.Reader.<init>(Reader.java:133)
        at com.maxmind.db.Reader.<init>(Reader.java:90)
        at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:89)
        at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:62)
        at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:216)
        at net.kollnig.missioncontrol.details.CountriesFragment.getHostCountriesCount(CountriesFragment.java:93)
        at net.kollnig.missioncontrol.details.CountriesFragment.lambda$onViewCreated$2$CountriesFragment(CountriesFragment.java:150)
        at net.kollnig.missioncontrol.details.-$$Lambda$CountriesFragment$mE06RLrgqjwL6-jcnPUwTuKp2x8.run(lambda)
        at java.lang.Thread.run(Thread.java:761)`

I open your library as follows:

    InputStream database = context.getAssets().open("GeoLite2-Country.mmdb");
    DatabaseReader reader = new DatabaseReader.Builder(database).build();

The second instruction then throws the above error.

**Comment by oschwald** [comment]
It appears that Android 7 is missing implementations of the relevant Java 8 methods. According to [the docs](https://developer.android.com/reference/java/lang/reflect/Executable#getParameterCount()), this method was added in API level 26, which corresponds to the platform version 8.0.0. I would recommend either continuing to use 2.14 of this library or targeting a newer version of Android.

**Comment by kasnder** [comment]
Thanks for clarifying!

**Comment by hazhir** [comment]
Hi, I wanted to bring your attention to an issue we encountered after updating to Version 4 of the library. It appears that the crash on Android 7 has resurfaced with this new version. However, I wanted to highlight that this issue was fixed in [Version 2 ](https://github.com/emanuele-f/MaxMind-DB-Reader-java/commit/778acb6fc055547eeb7f214d6903866855bb8887)of the MaxMind-DB-Reader library.

Upon investigating the problem, it seems that in Version 4 of the library, you are using Version 3 of MaxMind-DB-Reader, which appears to be causing the problem with the [Decoder](https://github.com/maxmind/MaxMind-DB-Reader-java/blob/27f6206746f94f8cc2e77cd3c2bb0ad1c06eb24d/src/main/java/com/maxmind/db/Decoder.java#L402) class. It seems that the changes introduced in Version 2 were not brought over to Version 3, which might be the root cause of the issue.

I kindly request your assistance in addressing this matter. Could you please look into fixing this issue and ensuring that the necessary changes from Version 2 are incorporated into Version 3 of MaxMind-DB?

**Comment by oschwald** [comment]
That change was not part of our release. Please see [this comment](https://github.com/maxmind/MaxMind-DB-Reader-java/pull/96#issuecomment-981853748). This library currently requires Java 11 support. The API you are referencing was introduced in Java 8. Even if that particular issue is fixed, it is likely that other things would break. If you need to support old Android versions that don't fully support Java 11, I would suggest using an older version of this library.
